exports.el = {
    companyDiv: '.form-group',
    companyInput: 'input[type="search"]',
    modalCreateCompanyTitle: 'h3.popover-title',
    modalCreateCompanySegmentDiv: '.form-group',
    modalCreateCompanySegmentInput: 'input[type="search"]',
    modalCreateCompanyOriginDiv: '.form-group',
    modalCreateCompanyOriginInput: 'input[type="search"]',
    modalCreateCompanyEmail: '.popover input[name="contact_email"]',
    modalCreateCompanyTel: '.popover input[name="contact_phones"]',
    modalCreateCompanySubmit: '.popover button[title="Submit"]',
    name: 'input[name="contact_name"]',
    tel: 'input[name="contact_phones"]',
    email: 'input[name="contact_email"]',
    roleDiv: '.form-group',
    roleInput: 'input[type="search"]',
    departmentDiv: '.form-group',
    departmentInput: 'input[type="search"]',
    otherInfoSection: 'div[name="section.name"] a',
    cpf: 'input[name="contact_cpf"]',
    birthDate: 'input[name="contact_birthday"]',
    obs: 'textarea[name="contact_note"]',
    newPersonTitle: 'new-contact-page-side-menu .font-very-big',
    submit: 'aside button',
};
