exports.el = {
    title: 'input[name="deal_title"]',
    price: 'input[name="deal_amount"]',
    contactDiv: '.form-group',
    contactInput: 'input[type="search"]',
    originDiv: '.form-group',
    originInput: 'input[type="search"]',
    otherInfoSection: 'div[name="section.name"] a',
    otherUsersDiv: '.form-group',
    otherUsersInput: 'input[type="search"]',
    productsDiv: '.form-group',
    productsInput: 'input[type="search"]',
    submit: '.modal-footer .button-action',
    modalCreateContactTitle: 'h3.popover-title',
    modalCreateContactRoleDiv: '.form-group',
    modalCreateContactRoleInput: 'input[type="search"]',
    modalCreateContactDepartmentDiv: '.popover .form-group',
    modalCreateContactDepartmentInput: 'input[type="search"]',
    modalCreateContactEmail: '.popover input[name="contact_email"]',
    modalCreateContactTel: '.popover input[name="contact_phones"]',
    modalCreateContactSubmit: '.popover button[title="Submit"]',
    modalCrateProductGroupDiv: '.popover .form-group',
    modalCrateProductGroupInput: 'input[type="search"]',
    modalCreateProductCode: 'input[name="product_code"]',
    modalCreateProductPrice: 'input[name="product_unit_price"]',
    modalCreateProductSubmit: '.popover .button-action',
};
