exports.el = {
    title: 'span.font-title',
    name: 'input[name="contact_name"]',
    corporateName: 'input[name="contact_legal_name"]',
    segmentDiv: '.form-group',
    segmentInput: 'input[type="search"]',
    originDiv: '.form-group',
    originInput: 'input[type="search"]',
    cnpj: 'input[name="contact_cnpj"]',
    typeTelBtn: '.input-group-btn',
    typeTelItem: 'li a',
    tel: 'input[name="contact_phones"]',
    locationSection: 'div[name="section.name"] a',
    addressDiv: 'div[name="section.name"] .form-group',
    addressInput: 'input',
    complementDiv: 'div[name="section.name"] .form-group',
    complementInput: 'input',
    neighborhoodDiv: 'div[name="section.name"] .form-group',
    neighborhoodInput: 'input',
    postalCode: 'input[name="contact_zipcode"]',
    cityDiv: 'div[name="section.name"] .form-group',
    cityInput: 'input[type="search"]',
    otherInfoSection: 'div[name="section.name"] a',
    email: 'input[name="contact_email"]',
    website: 'input[name="contact_website"]',
    relationshipDiv: '.form-group',
    relationshipInput: 'input[type="search"]',
    obs: 'textarea[name="contact_note"]',
    submit: 'aside button',
    newCompanyTitle: 'new-contact-page-side-menu .font-very-big'
};
